name: Build App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install NPM dependencies
        run: npm i
      - run: npm run css
      - name: Install COMPOSER dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Cleanup build from unecessary files and folders
        run: rm -rf node_modules/ .git* composer.* package*.json
      - uses: actions/upload-artifact@v1
        with:
          name: beccashome
          path: .
